// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go
//
// Generated by this command:
//
//	mockgen -typed -source provider.go -destination configtest/mocks.gen.go -package configtest
//

// Package configtest is a generated GoMock package.
package configtest

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Config mocks base method.
func (m *MockProvider) Config(ctx context.Context) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config", ctx)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Config indicates an expected call of Config.
func (mr *MockProviderMockRecorder) Config(ctx any) *MockProviderConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockProvider)(nil).Config), ctx)
	return &MockProviderConfigCall{Call: call}
}

// MockProviderConfigCall wrap *gomock.Call
type MockProviderConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderConfigCall) Return(arg0 map[string]string, arg1 error) *MockProviderConfigCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderConfigCall) Do(f func(context.Context) (map[string]string, error)) *MockProviderConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderConfigCall) DoAndReturn(f func(context.Context) (map[string]string, error)) *MockProviderConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FetchConfig mocks base method.
func (m *MockProvider) FetchConfig(ctx context.Context) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchConfig", ctx)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchConfig indicates an expected call of FetchConfig.
func (mr *MockProviderMockRecorder) FetchConfig(ctx any) *MockProviderFetchConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchConfig", reflect.TypeOf((*MockProvider)(nil).FetchConfig), ctx)
	return &MockProviderFetchConfigCall{Call: call}
}

// MockProviderFetchConfigCall wrap *gomock.Call
type MockProviderFetchConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderFetchConfigCall) Return(arg0 map[string]string, arg1 error) *MockProviderFetchConfigCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderFetchConfigCall) Do(f func(context.Context) (map[string]string, error)) *MockProviderFetchConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderFetchConfigCall) DoAndReturn(f func(context.Context) (map[string]string, error)) *MockProviderFetchConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockDynamicConfigManager is a mock of DynamicConfigManager interface.
type MockDynamicConfigManager struct {
	ctrl     *gomock.Controller
	recorder *MockDynamicConfigManagerMockRecorder
	isgomock struct{}
}

// MockDynamicConfigManagerMockRecorder is the mock recorder for MockDynamicConfigManager.
type MockDynamicConfigManagerMockRecorder struct {
	mock *MockDynamicConfigManager
}

// NewMockDynamicConfigManager creates a new mock instance.
func NewMockDynamicConfigManager(ctrl *gomock.Controller) *MockDynamicConfigManager {
	mock := &MockDynamicConfigManager{ctrl: ctrl}
	mock.recorder = &MockDynamicConfigManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamicConfigManager) EXPECT() *MockDynamicConfigManagerMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockDynamicConfigManager) GetConfig(key any) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", key)
	ret0, _ := ret[0].(any)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockDynamicConfigManagerMockRecorder) GetConfig(key any) *MockDynamicConfigManagerGetConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockDynamicConfigManager)(nil).GetConfig), key)
	return &MockDynamicConfigManagerGetConfigCall{Call: call}
}

// MockDynamicConfigManagerGetConfigCall wrap *gomock.Call
type MockDynamicConfigManagerGetConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDynamicConfigManagerGetConfigCall) Return(arg0 any) *MockDynamicConfigManagerGetConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDynamicConfigManagerGetConfigCall) Do(f func(any) any) *MockDynamicConfigManagerGetConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDynamicConfigManagerGetConfigCall) DoAndReturn(f func(any) any) *MockDynamicConfigManagerGetConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RegisterConfig mocks base method.
func (m *MockDynamicConfigManager) RegisterConfig(key any, factory func() any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterConfig", key, factory)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterConfig indicates an expected call of RegisterConfig.
func (mr *MockDynamicConfigManagerMockRecorder) RegisterConfig(key, factory any) *MockDynamicConfigManagerRegisterConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterConfig", reflect.TypeOf((*MockDynamicConfigManager)(nil).RegisterConfig), key, factory)
	return &MockDynamicConfigManagerRegisterConfigCall{Call: call}
}

// MockDynamicConfigManagerRegisterConfigCall wrap *gomock.Call
type MockDynamicConfigManagerRegisterConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDynamicConfigManagerRegisterConfigCall) Return(arg0 error) *MockDynamicConfigManagerRegisterConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDynamicConfigManagerRegisterConfigCall) Do(f func(any, func() any) error) *MockDynamicConfigManagerRegisterConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDynamicConfigManagerRegisterConfigCall) DoAndReturn(f func(any, func() any) error) *MockDynamicConfigManagerRegisterConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockDynamicConfigGetter is a mock of DynamicConfigGetter interface.
type MockDynamicConfigGetter[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockDynamicConfigGetterMockRecorder[T]
	isgomock struct{}
}

// MockDynamicConfigGetterMockRecorder is the mock recorder for MockDynamicConfigGetter.
type MockDynamicConfigGetterMockRecorder[T any] struct {
	mock *MockDynamicConfigGetter[T]
}

// NewMockDynamicConfigGetter creates a new mock instance.
func NewMockDynamicConfigGetter[T any](ctrl *gomock.Controller) *MockDynamicConfigGetter[T] {
	mock := &MockDynamicConfigGetter[T]{ctrl: ctrl}
	mock.recorder = &MockDynamicConfigGetterMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamicConfigGetter[T]) EXPECT() *MockDynamicConfigGetterMockRecorder[T] {
	return m.recorder
}

// Get mocks base method.
func (m *MockDynamicConfigGetter[T]) Get() T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(T)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockDynamicConfigGetterMockRecorder[T]) Get() *MockDynamicConfigGetterGetCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDynamicConfigGetter[T])(nil).Get))
	return &MockDynamicConfigGetterGetCall[T]{Call: call}
}

// MockDynamicConfigGetterGetCall wrap *gomock.Call
type MockDynamicConfigGetterGetCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDynamicConfigGetterGetCall[T]) Return(arg0 T) *MockDynamicConfigGetterGetCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDynamicConfigGetterGetCall[T]) Do(f func() T) *MockDynamicConfigGetterGetCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDynamicConfigGetterGetCall[T]) DoAndReturn(f func() T) *MockDynamicConfigGetterGetCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
