// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go
//
// Generated by this command:
//
//	mockgen -typed -source provider.go -destination provider.mock.gen.go -package config
//

// Package config is a generated GoMock package.
package config

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Config mocks base method.
func (m *MockProvider) Config(ctx context.Context) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config", ctx)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Config indicates an expected call of Config.
func (mr *MockProviderMockRecorder) Config(ctx any) *MockProviderConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockProvider)(nil).Config), ctx)
	return &MockProviderConfigCall{Call: call}
}

// MockProviderConfigCall wrap *gomock.Call
type MockProviderConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderConfigCall) Return(arg0 map[string]string, arg1 error) *MockProviderConfigCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderConfigCall) Do(f func(context.Context) (map[string]string, error)) *MockProviderConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderConfigCall) DoAndReturn(f func(context.Context) (map[string]string, error)) *MockProviderConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FetchConfig mocks base method.
func (m *MockProvider) FetchConfig(ctx context.Context) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchConfig", ctx)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchConfig indicates an expected call of FetchConfig.
func (mr *MockProviderMockRecorder) FetchConfig(ctx any) *MockProviderFetchConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchConfig", reflect.TypeOf((*MockProvider)(nil).FetchConfig), ctx)
	return &MockProviderFetchConfigCall{Call: call}
}

// MockProviderFetchConfigCall wrap *gomock.Call
type MockProviderFetchConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderFetchConfigCall) Return(arg0 map[string]string, arg1 error) *MockProviderFetchConfigCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderFetchConfigCall) Do(f func(context.Context) (map[string]string, error)) *MockProviderFetchConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderFetchConfigCall) DoAndReturn(f func(context.Context) (map[string]string, error)) *MockProviderFetchConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockDynamicConfigManager is a mock of DynamicConfigManager interface.
type MockDynamicConfigManager struct {
	ctrl     *gomock.Controller
	recorder *MockDynamicConfigManagerMockRecorder
	isgomock struct{}
}

// MockDynamicConfigManagerMockRecorder is the mock recorder for MockDynamicConfigManager.
type MockDynamicConfigManagerMockRecorder struct {
	mock *MockDynamicConfigManager
}

// NewMockDynamicConfigManager creates a new mock instance.
func NewMockDynamicConfigManager(ctrl *gomock.Controller) *MockDynamicConfigManager {
	mock := &MockDynamicConfigManager{ctrl: ctrl}
	mock.recorder = &MockDynamicConfigManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamicConfigManager) EXPECT() *MockDynamicConfigManagerMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockDynamicConfigManager) GetConfig(key any) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", key)
	ret0, _ := ret[0].(any)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockDynamicConfigManagerMockRecorder) GetConfig(key any) *MockDynamicConfigManagerGetConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockDynamicConfigManager)(nil).GetConfig), key)
	return &MockDynamicConfigManagerGetConfigCall{Call: call}
}

// MockDynamicConfigManagerGetConfigCall wrap *gomock.Call
type MockDynamicConfigManagerGetConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDynamicConfigManagerGetConfigCall) Return(arg0 any) *MockDynamicConfigManagerGetConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDynamicConfigManagerGetConfigCall) Do(f func(any) any) *MockDynamicConfigManagerGetConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDynamicConfigManagerGetConfigCall) DoAndReturn(f func(any) any) *MockDynamicConfigManagerGetConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RegisterConfig mocks base method.
func (m *MockDynamicConfigManager) RegisterConfig(key any, factory func() any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterConfig", key, factory)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterConfig indicates an expected call of RegisterConfig.
func (mr *MockDynamicConfigManagerMockRecorder) RegisterConfig(key, factory any) *MockDynamicConfigManagerRegisterConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterConfig", reflect.TypeOf((*MockDynamicConfigManager)(nil).RegisterConfig), key, factory)
	return &MockDynamicConfigManagerRegisterConfigCall{Call: call}
}

// MockDynamicConfigManagerRegisterConfigCall wrap *gomock.Call
type MockDynamicConfigManagerRegisterConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDynamicConfigManagerRegisterConfigCall) Return(arg0 error) *MockDynamicConfigManagerRegisterConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDynamicConfigManagerRegisterConfigCall) Do(f func(any, func() any) error) *MockDynamicConfigManagerRegisterConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDynamicConfigManagerRegisterConfigCall) DoAndReturn(f func(any, func() any) error) *MockDynamicConfigManagerRegisterConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RegisterConfigWithNotify mocks base method.
func (m *MockDynamicConfigManager) RegisterConfigWithNotify(key any, factory func() any) (CallbackAdder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterConfigWithNotify", key, factory)
	ret0, _ := ret[0].(CallbackAdder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterConfigWithNotify indicates an expected call of RegisterConfigWithNotify.
func (mr *MockDynamicConfigManagerMockRecorder) RegisterConfigWithNotify(key, factory any) *MockDynamicConfigManagerRegisterConfigWithNotifyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterConfigWithNotify", reflect.TypeOf((*MockDynamicConfigManager)(nil).RegisterConfigWithNotify), key, factory)
	return &MockDynamicConfigManagerRegisterConfigWithNotifyCall{Call: call}
}

// MockDynamicConfigManagerRegisterConfigWithNotifyCall wrap *gomock.Call
type MockDynamicConfigManagerRegisterConfigWithNotifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDynamicConfigManagerRegisterConfigWithNotifyCall) Return(arg0 CallbackAdder, arg1 error) *MockDynamicConfigManagerRegisterConfigWithNotifyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDynamicConfigManagerRegisterConfigWithNotifyCall) Do(f func(any, func() any) (CallbackAdder, error)) *MockDynamicConfigManagerRegisterConfigWithNotifyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDynamicConfigManagerRegisterConfigWithNotifyCall) DoAndReturn(f func(any, func() any) (CallbackAdder, error)) *MockDynamicConfigManagerRegisterConfigWithNotifyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCallbackAdder is a mock of CallbackAdder interface.
type MockCallbackAdder struct {
	ctrl     *gomock.Controller
	recorder *MockCallbackAdderMockRecorder
	isgomock struct{}
}

// MockCallbackAdderMockRecorder is the mock recorder for MockCallbackAdder.
type MockCallbackAdderMockRecorder struct {
	mock *MockCallbackAdder
}

// NewMockCallbackAdder creates a new mock instance.
func NewMockCallbackAdder(ctrl *gomock.Controller) *MockCallbackAdder {
	mock := &MockCallbackAdder{ctrl: ctrl}
	mock.recorder = &MockCallbackAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCallbackAdder) EXPECT() *MockCallbackAdderMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockCallbackAdder) Add(arg0 func(any)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", arg0)
}

// Add indicates an expected call of Add.
func (mr *MockCallbackAdderMockRecorder) Add(arg0 any) *MockCallbackAdderAddCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCallbackAdder)(nil).Add), arg0)
	return &MockCallbackAdderAddCall{Call: call}
}

// MockCallbackAdderAddCall wrap *gomock.Call
type MockCallbackAdderAddCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCallbackAdderAddCall) Return() *MockCallbackAdderAddCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCallbackAdderAddCall) Do(f func(func(any))) *MockCallbackAdderAddCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCallbackAdderAddCall) DoAndReturn(f func(func(any))) *MockCallbackAdderAddCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockDynamicConfigGetter is a mock of DynamicConfigGetter interface.
type MockDynamicConfigGetter[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockDynamicConfigGetterMockRecorder[T]
	isgomock struct{}
}

// MockDynamicConfigGetterMockRecorder is the mock recorder for MockDynamicConfigGetter.
type MockDynamicConfigGetterMockRecorder[T any] struct {
	mock *MockDynamicConfigGetter[T]
}

// NewMockDynamicConfigGetter creates a new mock instance.
func NewMockDynamicConfigGetter[T any](ctrl *gomock.Controller) *MockDynamicConfigGetter[T] {
	mock := &MockDynamicConfigGetter[T]{ctrl: ctrl}
	mock.recorder = &MockDynamicConfigGetterMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamicConfigGetter[T]) EXPECT() *MockDynamicConfigGetterMockRecorder[T] {
	return m.recorder
}

// Get mocks base method.
func (m *MockDynamicConfigGetter[T]) Get() T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(T)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockDynamicConfigGetterMockRecorder[T]) Get() *MockDynamicConfigGetterGetCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDynamicConfigGetter[T])(nil).Get))
	return &MockDynamicConfigGetterGetCall[T]{Call: call}
}

// MockDynamicConfigGetterGetCall wrap *gomock.Call
type MockDynamicConfigGetterGetCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDynamicConfigGetterGetCall[T]) Return(arg0 T) *MockDynamicConfigGetterGetCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDynamicConfigGetterGetCall[T]) Do(f func() T) *MockDynamicConfigGetterGetCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDynamicConfigGetterGetCall[T]) DoAndReturn(f func() T) *MockDynamicConfigGetterGetCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockDynamicConfigGetterWithNotify is a mock of DynamicConfigGetterWithNotify interface.
type MockDynamicConfigGetterWithNotify[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockDynamicConfigGetterWithNotifyMockRecorder[T]
	isgomock struct{}
}

// MockDynamicConfigGetterWithNotifyMockRecorder is the mock recorder for MockDynamicConfigGetterWithNotify.
type MockDynamicConfigGetterWithNotifyMockRecorder[T any] struct {
	mock *MockDynamicConfigGetterWithNotify[T]
}

// NewMockDynamicConfigGetterWithNotify creates a new mock instance.
func NewMockDynamicConfigGetterWithNotify[T any](ctrl *gomock.Controller) *MockDynamicConfigGetterWithNotify[T] {
	mock := &MockDynamicConfigGetterWithNotify[T]{ctrl: ctrl}
	mock.recorder = &MockDynamicConfigGetterWithNotifyMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamicConfigGetterWithNotify[T]) EXPECT() *MockDynamicConfigGetterWithNotifyMockRecorder[T] {
	return m.recorder
}

// Get mocks base method.
func (m *MockDynamicConfigGetterWithNotify[T]) Get() T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(T)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockDynamicConfigGetterWithNotifyMockRecorder[T]) Get() *MockDynamicConfigGetterWithNotifyGetCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDynamicConfigGetterWithNotify[T])(nil).Get))
	return &MockDynamicConfigGetterWithNotifyGetCall[T]{Call: call}
}

// MockDynamicConfigGetterWithNotifyGetCall wrap *gomock.Call
type MockDynamicConfigGetterWithNotifyGetCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDynamicConfigGetterWithNotifyGetCall[T]) Return(arg0 T) *MockDynamicConfigGetterWithNotifyGetCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDynamicConfigGetterWithNotifyGetCall[T]) Do(f func() T) *MockDynamicConfigGetterWithNotifyGetCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDynamicConfigGetterWithNotifyGetCall[T]) DoAndReturn(f func() T) *MockDynamicConfigGetterWithNotifyGetCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RegisterCallback mocks base method.
func (m *MockDynamicConfigGetterWithNotify[T]) RegisterCallback(arg0 func(T)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterCallback", arg0)
}

// RegisterCallback indicates an expected call of RegisterCallback.
func (mr *MockDynamicConfigGetterWithNotifyMockRecorder[T]) RegisterCallback(arg0 any) *MockDynamicConfigGetterWithNotifyRegisterCallbackCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterCallback", reflect.TypeOf((*MockDynamicConfigGetterWithNotify[T])(nil).RegisterCallback), arg0)
	return &MockDynamicConfigGetterWithNotifyRegisterCallbackCall[T]{Call: call}
}

// MockDynamicConfigGetterWithNotifyRegisterCallbackCall wrap *gomock.Call
type MockDynamicConfigGetterWithNotifyRegisterCallbackCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDynamicConfigGetterWithNotifyRegisterCallbackCall[T]) Return() *MockDynamicConfigGetterWithNotifyRegisterCallbackCall[T] {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDynamicConfigGetterWithNotifyRegisterCallbackCall[T]) Do(f func(func(T))) *MockDynamicConfigGetterWithNotifyRegisterCallbackCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDynamicConfigGetterWithNotifyRegisterCallbackCall[T]) DoAndReturn(f func(func(T))) *MockDynamicConfigGetterWithNotifyRegisterCallbackCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
